name: Auto Tag
on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-tags: true
          # otherwise, following workflows won't run. See https://github.com/orgs/community/discussions/25702
          
      - name: Auto Tag
        run: |
          version=`grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3`
          git tag v$version || true
          git push --tags || true
